site_name: CEMAS
site_url: https://ahoune-sane.netlify.app
site_description: Pour le CEM Ahoune Sane
site_author: Ibrahima Sarr
# repo_url: https://github.com/sarrIbou/sarr-mkdocs
repo_name: sarr-mkdocs
edit_uri: edit/master/docs/
theme: 
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/taureau.png
  favicon: assets/taureau.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: primary
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@sarrIbou
      
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kisarrweb


copyright: Copyright &copy; 2024 CEM Ahoune Sane










